---
name: "\U0001F41E  Bug Report"
description: Report any identified bugs.
title: 'Bug: '
labels: [bug]
# assignees: ''
body:
  - type: input
    attributes:
      label: "Orb version"
      description: |
        Which version of `dokku/dokku` are you using?
      placeholder: "1.0.0"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Current behavior"
      description: "How does the issue manifest?"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Minimum reproduction config"
      description: "Enter a URL to a failed build or write a config example to reproduce the issue"
      placeholder: "https://app.circleci.com/..."

  - type: textarea
    attributes:
      label: "Other"
      description: |
        Anything else you want to share?
