---
docker:
  - image: dokku/ci-docker-image:<<parameters.tag>>'

parameters:
  tag:
    default: 0.2.1
    description: >
      Pick a specific dokku/ci-docker-image image variant:
      https://hub.docker.com/r/dokku/ci-docker-image/tags
    type: string
