---
description: >
  An executor that provides the proper deploy
  tools to interact with a remote Dokku host

docker:
  - image: dokku/ci-docker-image:<<parameters.tag>>

parameters:
  tag:
    default: 0.4.0
    description: >
      Pick a specific dokku/ci-docker-image image variant:
      https://hub.docker.com/r/dokku/ci-docker-image/tags
    type: string
